spring.application.name=prepzone-backend


server.port=8272

spring.datasource.url=jdbc:postgresql://localhost:5432/prepzone
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.context-path=/prepzone


app.jwtSecret=ThisIsA256BitSecretKeyForJWT1234567890 
app.jwtExpirationMs=86400000             


# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

